### ISSUE TITLE
about litex_setup update fail

### ISSUE THREAD

**Issue by akioolin** [litex-hub/pythondata-misc-usb_ohci#1]
Hi, 

It is very good to see usb ohci ip integrated into LiteX. but there is a small point need to be addressed. 
when using litex_setup to update litex, the pythondata-misc-usb_ohci will fail. 
It seems no master in branch. 

the following log is the fail message.

[updating pythondata-misc-usb_ohci]...
error: pathspec 'master' did not match any file(s) known to git

BR, Akio

**Comment by Dolu1990** [comment]
Hoo the main branch is main, not master. I'm not sure where this should be fix.

**Comment by Dolu1990** [comment]
I created a master branch in this repo, normaly it should work now.
@enjoy-digital Can you set the master branch as default one ? (i don't have the rights)

**Comment by mithro** [comment]
I have updated the default branch to be `master`.

**Comment by akioolin** [comment]
Hi:

after git pull in the pythondata-misc-usb_ohci, litex_setup.py update could update without error.

Many Thanks.

BR, Akio
